### ISSUE TITLE
"[CrashPlanEngine] starting..." errors on latest version

### ISSUE THREAD

**Issue by moorsey** [jlesage/docker-crashplan-pro#188]
Have seen a few similar reports here, non that seem to lead to a resolution, so just adding mine here, to see what others are experiencing and hopefully get to the bottom of things!

As I have done previously, very smoothly, I binned and re-created my container last week, to move to the latest version.  SInce doing so, I have been un-able to get the container to start, with repeated "[CrashPlanEngine] starting..." in the log.

Looking in the service log, I see a ton of what look like Java type erros, being recorded every time it attempts to start the service: https://pastebin.com/A6ezVpBk

Key lines seem to be:

`[07.11.19 16:48:59.712 ERROR main                                         ] com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL`

`STACKTRACE:: com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL`

Currently starting with 4GB of memory, which has been working fine up until now.  Tried upping to 6GB, but still wouldn't start.

Have also tried cleaning the config folder, to see if it would start as a fresh container, but the same seems to happen, won't start

Any thought's on a way forward much appreciated!

**Comment by jlesage** [comment]
I think this issue occurs only when you use your own encryption key.  However, it's not clear if this issue is with the container or with the CP itself.

I would try to chat with CrashPlan support team to get their input on this.  Just make sure to *not* say your are running CP in a container: they are quick to close the discussion telling this is not supported.  If they want you to confirm your Linux distribution, just tell it's Ubuntu (CP in the container uses libraries from Ubuntu).

**Comment by gokuu** [comment]
I also have the same situation, t happened to me when upgrading from v2.6.2, and I made that mistake, of telling them that I was running inside docker. 

I can try to reach them again, but if they have any history on their ticket system, it will be immediately rejected

**Comment by moorsey** [comment]
@jlesage, many thanks, standard setup here, so not sure about any encryption keys in use

Contacted Crashplan, didn't mention docker but did mention "headless", which is also a bad word over there.  Still in comms with them, will update

This does seem unlikely to be their issue though, I can wipe out my config folder on my server and install from scratch and still get the same issue, so must be a hangover or something in there somewhere stopping things working.  That is what it feels like anyway

**Comment by moorsey** [comment]
Just to add to this, been looking through the logs again.

`[08.08.19 10:51:59.915 INFO  main           com.backup42.service.CPService] *****  STOPPING  *****
[08.08.19 10:51:59.920 INFO  ool-worker-3   com.backup42.service.CPService] SHUTDOWN:: Stopping service...
[08.08.19 10:51:59.928 WARN  Thread-0       com.backup42.service.CPService] SHUTDOWN:: Unable to stop threads (cleanup), java.util.concurrent.ExecutionException: com.code42.exception.DebugRuntimeException: Unable to persist ServiceModel, modelFilename=/usr/local/crashplan/conf/service.model, byteCount=null`

Looked for "service.model" and can only see it located in a backup I made of the Crashplan config directory, but not the currently in use one, so seems to get wiped when starting the container?  Copied it over but made no difference.

While crashplan is trying to start, top shows huge CPU usage also, FYI

Had a Google around for this service.model error and found this:

https://success.code42.com/communities/community-home/digestviewer/viewthread?MessageKey=9f6103bd-dca9-4401-8dad-9756afff78e1&CommunityKey=7cfc64c4-3037-46a4-83a5-20907f573246&tab=digestviewer

Mentions upgrading to V7, which this container already is.

**Comment by jlesage** [comment]
@gokuu, I think you can try to contact them again.

@moorsey, I've seen some issues that were caused by settings/data pushed from CP servers.  So starting from scratch doesn't confirm on which side the problem is.  What you could try is to see if you reproduce with a different/new account...

**Comment by gokuu** [comment]
Hey, 

I think my problem has been fixed. Here's how:
I had my docker containers running on a secondary HDD. This was also impacting my Plex container, which was unable to transcode anything to play on iOS devices.
This HDD was mounted using `auto,defaults,users` options. 
Remounted using `auto,defaults,users,exec`, and the container started working with the latest version.

@moorsey are you running on a similar setup? If you are, maybe this can help?

**Comment by moorsey** [comment]
Afraid not.  I am running Openmediavault, which mounts multiple HDDs into folders, Crashplan is set to the root folder of all of the HDDs, so I can backup files across the whole system.

There are no mount options for HDDs in openmediavault

Tried to reset all permissions on the folder where my docker stuff lives, but still no joy

Thanks for posting this tip though!

**Comment by daximus522** [comment]
I'm at a complete loss on this one... has been happening for over a month now after years of no issues.  I've even rebuilt my entire NAS to be based upon ubuntu after Code42 said debian wasn't supported.  I execute all my containers via Rancher (ugpraded to 1.6.28 to try and solve this problem) and ever since this problem started whenever I stop the container it kills all the networking on the host.  I have to reboot it before anything accessible.  I map /var/lib/docker to a second drive and made sure it had defaults (which includes exec) and even explicitly set exec.   Has anyone else gotten past this issue?

**Comment by jlesage** [comment]
Great, glade to know that it's now working for you.

**Comment by moorsey** [comment]
Thanks for the suggestion @daximus522 

I tried this, but continue to get the same error.  Can I confirm the commands you ran to acheive this, just in case I'm missing something.  This is what I have just tried:

`docker volume create crashplan_config

docker run -d --name=crashplan-pro -p 5888:5800 -v crashplan_config:/config:rw -v /sharedfolders:/storage:ro -e TZ=Europe/London -e KEEP_APP_RUNNING=1 -e USER_ID=1000 -e GROUP_ID=100 -e CRASHPLAN_SRV_MAX_MEM=4G jlesage/crashplan-pro
`

**Comment by moorsey** [comment]
Still struggling with this, just tidied and re-ran my container creation script, added the "CLEAN_TMP_DIR" variable also which I spotted when re-reading the docs

```
docker run -d \
	--name=crashplan-pro \
	-p 5800:5800 \
	-v /sharedfolders/dockerdata2/crashplan:/config:rw \
	-v /sharedfolders:/storage:ro \
	-v CLEAN_TMP_DIR=1 \
	-e TZ=Europe/London \
	-e KEEP_APP_RUNNING=1 \
	-e USER_ID=1000 \
	-e GROUP_ID=100 \
	-e CRASHPLAN_SRV_MAX_MEM=4G \
	jlesage/crashplan-pro
```

Are there any other folders (Java etc) on the local machine I could clear out to try and fix this?  Still 200% CPU and repeated "crashplanengine starting" messages :(

**Comment by daximus522** [comment]
> Still struggling with this, just tidied and re-ran my container creation script, added the "CLEAN_TMP_DIR" variable also which I spotted when re-reading the docs
> 
> ```
> docker run -d \
> 	--name=crashplan-pro \
> 	-p 5800:5800 \
> 	-v /sharedfolders/dockerdata2/crashplan:/config:rw \
> 	-v /sharedfolders:/storage:ro \
> 	-v CLEAN_TMP_DIR=1 \
> 	-e TZ=Europe/London \
> 	-e KEEP_APP_RUNNING=1 \
> 	-e USER_ID=1000 \
> 	-e GROUP_ID=100 \
> 	-e CRASHPLAN_SRV_MAX_MEM=4G \
> 	jlesage/crashplan-pro
> ```
> 
> Are there any other folders (Java etc) on the local machine I could clear out to try and fix this? Still 200% CPU and repeated "crashplanengine starting" messages :(

Your command for 2 weeks ago looks like the solution that got mine to work... the only thing that I can think of that is different is I mounted /var/lib/docker (where the named volume is stored I think) to a complete separate drive from my equivalent of /sharedfolders

**Comment by moorsey** [comment]
Just to add to this, in case anyone stumbles over it this issue was almost certainty related to inodes / real time file watch problems.

For anyone coming across this, make sure you try all of the following:

Increase memory - https://support.code42.com/CrashPlan/6/Troubleshooting/Adjust_Code42_app_settings_for_memory_usage_with_large_backups
Increase inodes - https://support.code42.com/CrashPlan/4/Troubleshooting/Backups_stall_due_to_too_many_open_files
Increase real time file watch - https://support.code42.com/CrashPlan/6/Troubleshooting/Linux_real-time_file_watching_errors

Not running via docker currently, as re-purposed an older PC to run Crashplan during troubleshooting with Crashplan. But no doubt these would fix my issues, as they initially continued when everything was re-set on this PC from Docker, got there in the end!
