### ISSUE TITLE
v2.17.0 is not starting - error initializing JVM

### ISSUE THREAD

**Issue by neyrond** [jlesage/docker-crashplan-pro#378]
Cannot launch Crashplan after updating image to v2.17.0. The problem is reproducible with a new / minimal configuration.

This is can be seen in `engine_output.log` in v2.17.0
```
Initializing the JVM arguments.
Creating the Java virtual machine.
Number of arguments: 20
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

Launched v2.16.0 with a empty config, everything seems OK:
```
Initializing the JVM arguments.
Creating the Java virtual machine.
Number of arguments: 20
Java virtual machine created.
Starting service.
[05.28.22 05:23:36.473 INFO  main             com.code42.utils.ClassFinder] Loaded classpaths in 3018 ms

```

This is a docker configuration: 
```
docker run \
-d --privileged \
--name=crashplan-pro-test-2 \
-v /volume1/docker-appdata/crashplan-pro-test2:/config:rw \
-p 5802:5800 \
jlesage/crashplan-pro:latest
```

Device: DS918+
OS: DSM 7.0.1

**Comment by jlesage** [comment]
What is the problem exactly ?  The container is stopping itself ?
Do you have the container's log ?

**Comment by neyrond** [comment]
1. The container itself is starting
2. When I'm accessing it through the browser I see `Code42 cannot connect to its background service`
3. Container log is flooded with `[CrashPlanEngine] starting...` (repeated each second)
4. `log/ui.log` contains something like that:
```
2022-05-29T05:22:01.258Z - info: Retrying communication with service attempt 69
2022-05-29T05:22:02.260Z - info: File at /var/lib/crashplan/.ui_info not found.
2022-05-29T05:22:02.260Z - info: Retrying communication with service attempt 70
2022-05-29T05:22:03.168Z - info: Unable to communicate with the service. Timeout attempting to connect to the service
2022-05-29T05:22:03.186Z - error main: Uncaught Exception |  TypeError: this.setState is not a function
```
5. `log/engine_output.log` contains:

```
Initializing the JVM arguments.
Creating the Java virtual machine.
Number of arguments: 20
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
Launching as root
Paths:
  cwd:      /usr/local/crashplan
  appData:  /usr/local/crashplan
  jvm_args: /usr/local/crashplan/conf/jvm_args
JVM arguments in use:
-Dsun.jnu.encoding=UTF-8
-Dfile.encoding=UTF-8
-Dsun.net.inetaddr.ttl=300
-Dnetworkaddress.cache.ttl=300
-Dsun.net.inetaddr.negative.ttl=0
-Dnetworkaddress.cache.negative.ttl=0
-Dapp=Code42Service
-DappBaseName=Code42
-Djna.nosys=true
-Djava.awt.headless=true
-DCode42=Code42
-Dnashorn.args=--no-deprecation-warning
-Dc42.installation.enforcement.enabled=true
-XX:-ShrinkHeapInSteps
-XX:MaxHeapFreeRatio=30
-XX:MinHeapFreeRatio=15
-Djava.library.path=/usr/local/crashplan/nlib
-Djna.library.path=/usr/local/crashplan/nlib
-Dc42.log.config=/usr/local/crashplan/conf/service.log.xml
```

7. I encountered the same symptoms with my configuration that was working for years, until this update. Nothing changes if I start container without any config. I have tried increasing/decreasing memory - nothing changes.

**Comment by jlesage** [comment]
What about `engine_error.log` and `service.log.0` ?

**Comment by jlesage** [comment]
If you run the following command, do you see the engine crashing in loop?

```
docker run --rm jlesage/crashplan-pro:v2.17.0
```

**Comment by neyrond** [comment]
What I see is:
```
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
```

Whereas  `docker run --rm jlesage/crashplan-pro:v2.16.8` looks like a healthy start:
```
[services.d] starting app...
[app] starting CrashPlan for Small Business...
[services.d] done.```

**Comment by jlesage** [comment]
That's strange.  The command should have worked, since it creates and run a container without any configuration and external dependencies.

Is the Sinology and/or Docker up-to-date ?

**Comment by neyrond** [comment]
Yes, it's the latest Docker version available on Synology, and the latest DSM. Processor is Intel Celeron J3455  (x86).

Is it possible to enable additional logs?

**Comment by jlesage** [comment]
Everything should be in `engine_output.log`, `engine_error.log` and `service.log.0`.  The fact that there is nothing in `service.log.0` indicates that it's crashing very early.

What you could try is start the engine manually with strace:

- Login to the container: `docker exec -ti <container name> sh`.
- Install `strace`: `add-pkg strace`
- Start the engine: `strace -f /usr/local/crashplan/bin/startCrashPlanEngine.sh`
- Share the output.

**Comment by neyrond** [comment]
Here is result of strace:
[strace.log](https://github.com/jlesage/docker-crashplan-pro/files/8811213/strace.log)

**Comment by jlesage** [comment]
Ok, so the problem is that `/usr/local/crashplan/jre/lib/modules`, part of the image, is empty (it has a size of 0).

This is what I have on my side:

```
$ docker run --rm jlesage/crashplan-pro:latest ls -l /usr/local/crashplan/jre/lib/modules
-rwxr--r--    1 root     root      26831052 May 15 22:46 /usr/local/crashplan/jre/lib/modules
```

So it looks like the image is corrupted on your side.  Can you try to remove the image and download (pull) it again ?

**Comment by neyrond** [comment]
Wow, it helped! It's working now! Thank you!

I have removed all the images related to crashplan-pro:
```
docker image rm jlesage/crashplan-pro:v2.16.8
docker image rm jlesage/crashplan-pro:v2.17.0
docker image rm jlesage/crashplan-pro:latest
```
and removed the rest by their IDs (found by `docker image ls`)

Then ran `docker pull jlesage/crashplan-pro:latest`, and got strange results:
```
latest: Pulling from jlesage/crashplan-pro
97518928ae5f: Already exists
883f6e12ad1f: Already exists
1d6aaf800c31: Already exists
982593790b64: Already exists
a37f4162d62a: Already exists
67f44538fcb5: Already exists
857195453fb6: Already exists
a621b384285d: Already exists
8afd14b29c59: Already exists
011ebd122c7c: Already exists
eb5a04735bb4: Already exists
a96a42b95742: Already exists
dddf1d8793df: Already exists
4a6cdc657fd2: Already exists
a7f969044620: Already exists
37d6083c85c0: Extracting [=>                                                 ]  5.014MB/221.5MB
eb3bdae43c10: Download complete
2b8917245bbd: Download complete
2c6529437168: Download complete
08a1e27aaeab: Download complete
d67edcb4a930: Download complete
9cdbe3b8f1d0: Download complete
ba9c4e4840b7: Download complete
145558945f22: Download complete

```

1. Why somethings is still exists? Are these btfrs tricks?
2. Why where is no integrity checks in docker so that incomplete images can by run. 

Thank you very much for your help!

**Comment by jlesage** [comment]
Great that we found the problem!

> Why somethings is still exists? Are these btfrs tricks?

A Docker image is composed of multiple "layers". Layers that are shared between images (i.e. the baseimage) are not removed.  This is why you see that first layers already exist.

> Why where is no integrity checks in docker so that incomplete images can by run.

That's a good question.  Integrity check is done when the image is downloaded and extracted.  But once extracted, I guess that no other validation is done.
